name = "vue-jobs"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"

# 基本路由配置
[[routes]]
pattern = "/*"
zone_name = "vue-jobs"

# 静态资源缓存配置
[site.static]
include = ["dist/*"]
exclude = []
fallback_page = "/index.html"

# 可选的环境变量
[vars]
API_URL = "https://your-api-url.com"
